import { Box, Camera, Crosshair, Expand, Eye, Pause, Play, RefreshCw, Square, Video } from 'lucide-react'
import { Dropdown, Segmented, Tooltip } from 'antd'
import { useAppStore } from '../store/useAppStore'

export function SimulationView({ notify }: { notify: (text: string) => void }) {
  const { status, setStatus, speed, setSpeed, sensor } = useAppStore()
  const act = (next: typeof status, text: string) => { setStatus(next); notify(text) }
  // 下方 sim-viewport 是画面适配边界：未来可整体替换为 Three.js、Unity Canvas 或视频流播放器。
  return <section className="sim-panel"><div className="sim-toolbar"><div className="view-modes"><button className="active"><Box size={15} />漫游</button><button onClick={() => notify('自由视角接口已预留，等待仿真引擎接入')}><Eye size={15} />自由视角</button><button onClick={() => notify('跟随视角接口已预留，等待仿真引擎接入')}><Camera size={15} />跟随</button><button onClick={() => notify('第一人称接口已预留，等待视频流接入')}><Video size={15} />第一人称</button></div><div className="play-controls"><Tooltip title={status === 'paused' ? '继续' : '暂停'}><button className={status === 'paused' ? 'active' : ''} onClick={() => act(status === 'paused' ? 'running' : 'paused', status === 'paused' ? '仿真已继续' : '仿真已暂停')}>{status === 'paused' ? <Play size={16} /> : <Pause size={16} />}</button></Tooltip><Tooltip title="停止"><button onClick={() => act('stopped', '仿真已停止')}><Square size={15} /></button></Tooltip><Tooltip title="重置"><button onClick={() => { setStatus('running'); notify('仿真状态已重置（Mock）') }}><RefreshCw size={15} /></button></Tooltip><Segmented size="small" value={speed} onChange={(v) => { setSpeed(Number(v)); notify(`仿真倍速已切换为 ${v}×`) }} options={[{ label: '1×', value: 1 }, { label: '2×', value: 2 }, { label: '5×', value: 5 }]} /></div><Dropdown menu={{ items: [{ key: 'engine', label: 'Three.js / Unity 接口预留' }, { key: 'stream', label: 'ROS / WebSocket 视频流预留' }] }}><button><Expand size={15} />画面源</button></Dropdown></div>
  <div className="sim-viewport"><div className="ceiling-grid"/><div className="corridor"><div className="wall left-wall"><span className="door"/></div><div className="vanishing"/><div className="wall right-wall"><span className="window-fire"/><span className="fire fire-a"/><span className="fire fire-b"/></div><div className="floor-grid"/></div><div className="smoke smoke-one"/><div className="smoke smoke-two"/><div className="route-line"><span/><span/><span/><span/></div><div className="robot-visual"><div className="robot-body"><span className="sensor-head"/></div><i/><i/><i/><i/></div><div className="target-pin"><Crosshair size={18} />目标点 A-03</div><div className="danger-flag"><AlertMark />高温区域</div>{status !== 'running' && <div className="sim-overlay"><div>{status === 'paused' ? <Pause size={30} /> : <Square size={28} />}</div><strong>{status === 'paused' ? '仿真已暂停' : '仿真已停止'}</strong></div>}
  {sensor && <div className="telemetry"><strong>环境检测</strong><span>温度 <b>{sensor.temperature}°C</b></span><span>烟雾 <b>{sensor.smoke}</b></span><span>可见度 <b>{sensor.visibility} m</b></span><span>CO 浓度 <b>{sensor.co} ppm</b></span><span>氧浓度 <b>{sensor.oxygen}%</b></span></div>}
  <div className="sim-actions">{['添加目标', '清除目标', '设置禁区', '清除路径', '标记点', '测量距离'].map((label) => <button key={label} onClick={() => notify(`${label}接口已预留，等待仿真引擎接入`)}><Crosshair size={13} />{label}</button>)}</div></div></section>
}
function AlertMark() { return <span className="alert-mark">!</span> }
