import { useEffect, useState } from 'react'
import { Radio, ScanLine, ThermometerSun, Waves } from 'lucide-react'
import { Segmented } from 'antd'
import { Panel } from './Panel'
import { useAppStore } from '../store/useAppStore'

const options = [{ label: '多视图', value: 'all' }, { label: '第一视角 RGB', value: 'rgb' }, { label: '第一视角深度', value: 'depth' }, { label: '热成像', value: 'thermal' }, { label: '激光雷达', value: 'lidar' }]
const feeds = [{ id: 'rgb', label: '第一视角 RGB', icon: Radio }, { id: 'depth', label: '第一视角深度', icon: Waves }, { id: 'thermal', label: '热成像', icon: ThermometerSun }, { id: 'lidar', label: '激光雷达', icon: ScanLine }]
export function SensorPanel() { const { activeSensor, setSensor } = useAppStore(); const [depthFrame, setDepthFrame] = useState(0); useEffect(() => { if (activeSensor !== 'depth') return; const timer = window.setInterval(() => setDepthFrame((frame) => (frame + 1) % 3), 200); return () => window.clearInterval(timer) }, [activeSensor]); const visible = activeSensor === 'all' ? feeds : feeds.filter((f) => f.id === activeSensor); return <Panel title="传感器视图" extra={<span className="live-dot">● LIVE</span>}><Segmented block size="small" value={activeSensor} onChange={(v) => setSensor(String(v))} options={options} /><div className="sensor-mode-hint">{activeSensor === 'all' ? '多视图模式会同时绘制 4 路画面' : activeSensor === 'depth' ? '第一视角 · Gaussian 深度帧回放 · 640×360' : activeSensor === 'rgb' ? '第一视角 · Gaussian RGB' : '单路传感器视图'}</div><div className={`sensor-grid ${visible.length === 1 ? 'single' : ''}`}>{visible.map(({ id, label, icon: Icon }) => <div className={`sensor-feed ${id}`} key={id}><div className="feed-label"><Icon size={12} />{label}<span>{id === 'depth' ? 'FieryGS' : '30 FPS'}</span></div>{id === 'depth' ? <img className="gaussian-depth-frame" src={`/gaussian-depth/${String(depthFrame).padStart(3, '0')}.png`} alt="Gaussian 深度帧" /> : <div className="feed-art"><span className="sensor-corridor"/><span className="sensor-flame"/>{id === 'lidar' && <span className="radar-sweep"/>}</div>}</div>)}</div></Panel> }
